CREATE DATABASE Vitals;

CREATE TABLE BP (

systolic INT,

diastolic INT

);

CREATE TABLE Temperature (

temperature FLOAT

);

CREATE TABLE Pulse (

bpm INT,

oxygen INT

);

INSERT INTO BP VALUES(133,90);
INSERT INTO BP VALUES(128,82);
INSERT INTO BP VALUES(114,77);
INSERT INTO BP VALUES(139,80);
INSERT INTO BP VALUES(121,76);
INSERT INTO BP VALUES(140,90);

INSERT INTO Temperature VALUES(97.8);
INSERT INTO Temperature VALUES(98.4);
INSERT INTO Temperature VALUES(98.9);
INSERT INTO Temperature VALUES(97.0);
INSERT INTO Temperature VALUES(101.8);
INSERT INTO Temperature VALUES(96.9);

INSERT INTO Pulse VALUES(100,100);
INSERT INTO Pulse VALUES(160,97);
INSERT INTO Pulse VALUES(98,99);
INSERT INTO Pulse VALUES(139,94);
INSERT INTO Pulse VALUES(76,90);

SELECT * FROM BP, Temperature, Pulse;

DROP TABLE BP
DROP TABLE Temperature
DROP TABLE Pulse
